# Generated by Django 6.0.7 on 2026-07-18 06:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('icon', models.ImageField(upload_to='work/')),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='M', max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=100, verbose_name='Genre')),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=150)),
                ('duration_minutes', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
